-- ------ JOINING ON MULTIPLE FIELDS
SELECT *
FROM PROCEDUREHISTORY;

SELECT *
FROM PROCEDUREDETAILS;

SELECT *
FROM PROCEDUREHISTORY AS A
LEFT JOIN PROCEDUREDETAILS AS B
ON A.PROCEDURETYPE = B.PROCEDURETYPE
AND A.PROCEDURESUBCODE = B.PROCEDURESUBCODE;


-- ------ COMPLEX JOIN
SELECT *
FROM PETS AS A
INNER JOIN PROCEDUREHISTORY AS B
ON A.PETID = B.PETID
LEFT JOIN PROCEDUREDETAILS AS C
ON B.PROCEDURETYPE = C.PROCEDURETYPE
AND B.PROCEDURESUBCODE = C.PROCEDURESUBCODE;


-- ------ CLEANING UP YOUR JOINS
SELECT A.PETID,
       -- A.NAME,
       -- A.KIND,
       -- A.GENDER,
       -- A.AGE,
       A.OWNERID,
       B.PROCEDUREDATE,
       B.PROCEDURETYPE,
       B.PROCEDURESUBCODE,
       C.DESCRIPTION,
       C.PRICE
       
FROM PETS AS A
INNER JOIN PROCEDUREHISTORY AS B
ON A.PETID = B.PETID
LEFT JOIN PROCEDUREDETAILS AS C
ON B.PROCEDURETYPE = C.PROCEDURETYPE
AND B.PROCEDURESUBCODE = C.PROCEDURESUBCODE;